FROM resin/%%RESIN_MACHINE_NAME%%-python

# Update apt to install latest packages
RUN apt-get update

# install required packages
RUN apt-get install bluez bluez-firmware python-bluez

# define our working directory in the container
WORKDIR /usr/src/app

# copy all files in our root to the working directory
COPY . ./

# enable systemd init system in the container
ENV INITSYSTEM=on

# scan.sh will run when the container starts up on the device
CMD ["bash", "scan.sh"]
